program postal_to_FIPS
	local state_str_var `1'
	qui{
	capture gen statefips = .
	if _rc {
		noisily display "WARNING: statefips variable already exists. Making no changes"
	}
	else{
		replace statefips = 2  if `state_str_var' == "AK"
		replace statefips = 1  if `state_str_var' == "AL"
		replace statefips = 5  if `state_str_var' == "AR"
		replace statefips = 60 if `state_str_var' == "AS"
		replace statefips = 4  if `state_str_var' == "AZ"
		replace statefips = 6  if `state_str_var' == "CA"
		replace statefips = 8  if `state_str_var' == "CO"
		replace statefips = 9  if `state_str_var' == "CT"
		replace statefips = 11 if `state_str_var' == "DC"
		replace statefips = 10 if `state_str_var' == "DE"
		replace statefips = 12 if `state_str_var' == "FL"
		replace statefips = 13 if `state_str_var' == "GA"
		replace statefips = 66 if `state_str_var' == "GU"
		replace statefips = 15 if `state_str_var' == "HI"
		replace statefips = 19 if `state_str_var' == "IA"
		replace statefips = 16 if `state_str_var' == "ID"
		replace statefips = 17 if `state_str_var' == "IL"
		replace statefips = 18 if `state_str_var' == "IN"
		replace statefips = 20 if `state_str_var' == "KS"
		replace statefips = 21 if `state_str_var' == "KY"
		replace statefips = 22 if `state_str_var' == "LA"
		replace statefips = 25 if `state_str_var' == "MA"
		replace statefips = 24 if `state_str_var' == "MD"
		replace statefips = 23 if `state_str_var' == "ME"
		replace statefips = 26 if `state_str_var' == "MI"
		replace statefips = 27 if `state_str_var' == "MN"
		replace statefips = 29 if `state_str_var' == "MO"
		replace statefips = 28 if `state_str_var' == "MS"
		replace statefips = 30 if `state_str_var' == "MT"
		replace statefips = 37 if `state_str_var' == "NC"
		replace statefips = 38 if `state_str_var' == "ND"
		replace statefips = 31 if `state_str_var' == "NE"
		replace statefips = 33 if `state_str_var' == "NH"
		replace statefips = 34 if `state_str_var' == "NJ"
		replace statefips = 35 if `state_str_var' == "NM"
		replace statefips = 32 if `state_str_var' == "NV"
		replace statefips = 36 if `state_str_var' == "NY"
		replace statefips = 39 if `state_str_var' == "OH"
		replace statefips = 40 if `state_str_var' == "OK"
		replace statefips = 41 if `state_str_var' == "OR"
		replace statefips = 42 if `state_str_var' == "PA"
		replace statefips = 72 if `state_str_var' == "PR"
		replace statefips = 44 if `state_str_var' == "RI"
		replace statefips = 45 if `state_str_var' == "SC"
		replace statefips = 46 if `state_str_var' == "SD"
		replace statefips = 47 if `state_str_var' == "TN"
		replace statefips = 48 if `state_str_var' == "TX"
		replace statefips = 49 if `state_str_var' == "UT"
		replace statefips = 51 if `state_str_var' == "VA"
		replace statefips = 78 if `state_str_var' == "VI"
		replace statefips = 50 if `state_str_var' == "VT"
		replace statefips = 53 if `state_str_var' == "WA"
		replace statefips = 55 if `state_str_var' == "WI"
		replace statefips = 54 if `state_str_var' == "WV"
		replace statefips = 56 if `state_str_var' == "WY"
	}
	}
end
