program statename_to_FIPS
	local state_str_var `1'
	qui{
	capture gen statefips = .
	if _rc {
		noisily display "WARNING: statefips variable already exists. Making no changes"
	}
	else{
		replace statefips = 2  if `state_str_var' == "Alaska"
		replace statefips = 1  if `state_str_var' == "Alabama"
		replace statefips = 5  if `state_str_var' == "Arkansas"
		replace statefips = 60 if `state_str_var' == "American Samoa"
		replace statefips = 4  if `state_str_var' == "Arizona"
		replace statefips = 6  if `state_str_var' == "California"
		replace statefips = 8  if `state_str_var' == "Colorado"
		replace statefips = 9  if `state_str_var' == "CONNECTICUT" | `state_str_var' == "Connecticut"
		replace statefips = 11 if `state_str_var' == "District of Columbia"
		replace statefips = 10 if `state_str_var' == "Delaware"
		replace statefips = 12 if `state_str_var' == "Florida"
		replace statefips = 13 if `state_str_var' == "Georgia"
		replace statefips = 66 if `state_str_var' == "Guam"
		replace statefips = 15 if `state_str_var' == "Hawaii"
		replace statefips = 19 if `state_str_var' == "Iowa"
		replace statefips = 16 if `state_str_var' == "Idaho"
		replace statefips = 17 if `state_str_var' == "Illinois"
		replace statefips = 18 if `state_str_var' == "Indiana"
		replace statefips = 20 if `state_str_var' == "Kansas"
		replace statefips = 21 if `state_str_var' == "Kentucky"
		replace statefips = 22 if `state_str_var' == "Louisiana"
		replace statefips = 25 if `state_str_var' == "Massachusetts"
		replace statefips = 24 if `state_str_var' == "Maryland"
		replace statefips = 23 if `state_str_var' == "Maine"
		replace statefips = 26 if `state_str_var' == "Michicago"
		replace statefips = 27 if `state_str_var' == "Minnesota"
		replace statefips = 29 if `state_str_var' == "Missouri"
		replace statefips = 28 if `state_str_var' == "Mississippi"
		replace statefips = 30 if `state_str_var' == "Montana"
		replace statefips = 37 if `state_str_var' == "North Carolina"
		replace statefips = 38 if `state_str_var' == "North Dakota"
		replace statefips = 31 if `state_str_var' == "Nebraska"
		replace statefips = 33 if `state_str_var' == "New Hampshire"
		replace statefips = 34 if `state_str_var' == "New Jersey"
		replace statefips = 35 if `state_str_var' == "New Mexico"
		replace statefips = 32 if `state_str_var' == "Nevada"
		replace statefips = 36 if `state_str_var' == "New York"
		replace statefips = 39 if `state_str_var' == "Ohio"
		replace statefips = 40 if `state_str_var' == "Oklahoma"
		replace statefips = 41 if `state_str_var' == "Oregon"
		replace statefips = 42 if `state_str_var' == "Pennsylvania"
		replace statefips = 72 if `state_str_var' == "Puerto Rico"
		replace statefips = 44 if `state_str_var' == "Rhode Island"
		replace statefips = 45 if `state_str_var' == "South Carolina"
		replace statefips = 46 if `state_str_var' == "South Dakota"
		replace statefips = 47 if `state_str_var' == "Tennessee"
		replace statefips = 48 if `state_str_var' == "Texas"
		replace statefips = 49 if `state_str_var' == "Utah"
		replace statefips = 51 if `state_str_var' == "Virginia"
		replace statefips = 78 if `state_str_var' == "Virgin Islands"
		replace statefips = 50 if `state_str_var' == "Vermont"
		replace statefips = 53 if `state_str_var' == "Washington"
		replace statefips = 55 if `state_str_var' == "Wisconsin"
		replace statefips = 54 if `state_str_var' == "West Virginia"
		replace statefips = 56 if `state_str_var' == "Wyoming"
	}
	}
end
